In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("/home/vaibhav/Gemstone_Price/artifacts/train.csv")
df.head()

       id  carat      cut color clarity  depth  table     x     y     z  price
0   17070   1.01  Premium     E    VVS1   62.5   60.0  6.45  6.41  4.01  10053
1   71777   1.30  Premium     E     SI2   60.3   59.0  7.11  7.05  4.24   6296
2  177525   0.27    Ideal     E     VS1   61.5   57.0  4.15  4.18  2.56    577
3   30241   0.30    Ideal     F      IF   62.4   56.0  4.30  4.32  2.69    914
4  100756   0.72    Ideal     H    VVS1   61.9   56.0  5.75  5.79  3.57   3223

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191637 entries, 0 to 191636
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       191637 non-null  int64
 1   carat    191637 non-null  float64
 2   cut      191637 non-null  object
 3   color    191637 non-null  object
 4   clarity  191637 non-null  object
 5   depth    191637 non-null  float64
 6   table    191637 non-null  float64
 7   x        191637 non-null  float64
 8   y        191637 non-null  float64
 9   z        191637 non-null  float64
 10  price    191637 non-null  int64
dtypes: float64(6), int64(2), object(3)
memory usage: 16.1+ MB

In [13]:
df = df.drop(labels=['id'],axis=1)

In [14]:
df.isna().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
x          0
y          0
z          0
price      0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
numerical_columns = list(df.columns[df.dtypes!='object'])
categorical_columns = list(df.columns[df.dtypes=='object'])
print(f'Numerical Columns   : {numerical_columns}')
print(f'Categorical Columns : {categorical_columns}')

Numerical Columns   : ['carat', 'depth', 'table', 'x', 'y', 'z', 'price']
Categorical Columns : ['cut', 'color', 'clarity']

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
carat,191637.0,0.790601,0.462577,0.2,0.40,0.70,1.03,3.50
depth,191637.0,61.821127,1.081799,52.1,61.30,61.90,62.40,71.60
table,191637.0,57.228024,1.918868,49.0,56.00,57.00,58.00,79.00
x,191637.0,5.715092,1.109278,0.0,4.70,5.70,6.51,9.65
y,191637.0,5.719881,1.102191,0.0,4.71,5.72,6.51,10.01
z,191637.0,3.534150,0.688921,0.0,2.90,3.53,4.03,31.30
price,191637.0,3968.521048,4033.840436,326.0,950.00,2401.00,5407.00,18818.00